[tasks.init]
description = "miseの設定ファイルを追加します"
run = "touch mise.toml"

[tasks.setup-venv]
description = "Set up a Python virtual environment."
run = [
        "python3 -m venv .venv",
        "echo '[env]\n_.python.venv = \".venv\"' >> mise.toml",
        "mise trust"
    ]
